# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
            name: Add python project to path
            command: 'echo "$(realpath .)/app" > venv/lib/python3.8/site-packages/app.pth'
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
